name: Total Health Chiropractic Center
favicon: null
layout_spectrum: 0.85881
typography_spectrum: 0.9987
title: Total Health Chiropractic Center
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#152970'
    - '#f5e4c8'
    - '#af95ae'
    - '#8cb6ff'
    - '#766b71'
  brandStrength: 0.5
  lightness: 0.7065980168990791
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
