name: Total Health Chiropractic Center
favicon: null
layout_spectrum: 0.8288911881390959
typography_spectrum: 0.3687645890749991
title: Total Health Chiropractic Center
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5671560151968151
  lightness: 0.7065980168990791
  saturation: 0.6542778592556715
  rhythmicContrast: 0.6061705031897873
purpose: []
